#!/usr/bin/env bash
set -Eeuo pipefail

: "${DB_NAME:?DB_NAME is required}"
: "${DB_USER:?DB_USER is required}"
: "${DB_PASSWORD:?DB_PASSWORD is required}"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"
MIGRATIONS_DIR="${MIGRATIONS_DIR:-/migrations}"

export PGPASSWORD="$DB_PASSWORD"

echo "[migration] Starting (host=$DB_HOST, port=$DB_PORT, db=$DB_NAME, user=$DB_USER)"

psql_app() {
  psql \
    --host="$DB_HOST" \
    --port="$DB_PORT" \
    --username="$DB_USER" \
    --dbname="$DB_NAME" \
    --no-psqlrc \
    "$@"
}

# Wait until the target database accepts authenticated connections.
until psql_app --tuples-only --no-align --command='SELECT 1;' >/dev/null 2>&1; do
  echo "[migration] Waiting for PostgreSQL at $DB_HOST:$DB_PORT..."
  sleep 1
done

psql_app --set=ON_ERROR_STOP=1 <<'SQL'
CREATE TABLE IF NOT EXISTS public.migrations (
    id_migration bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_name text NOT NULL,
    migration_checksum char(64) NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_migrations_migration_name UNIQUE (migration_name)
);
SQL

SQL_FILES=()
if [[ ! -d "$MIGRATIONS_DIR" ]]; then
  echo "[migration] Directory $MIGRATIONS_DIR does not exist."
else
  # Sort files by the numeric component before the first dot.
  mapfile -t SQL_FILES < <(
    find "$MIGRATIONS_DIR" -maxdepth 1 -type f -name '*.sql' -printf '%f\n' \
      | LC_ALL=C sort -t'.' -k1,1n -k2,2
  )
fi

if (( ${#SQL_FILES[@]} == 0 )); then
  echo "[migration] No SQL migration files were found in $MIGRATIONS_DIR."
fi

for migration_name in "${SQL_FILES[@]}"; do
  # Required format: <number>.<description>.sql
  if [[ ! "$migration_name" =~ ^[0-9]+\.[A-Za-z0-9][A-Za-z0-9._-]*\.sql$ ]]; then
    echo "[migration] WARNING: '$migration_name' does not match '<number>.<description>.sql'; skipping it." >&2
    continue
  fi

  migration_file="$MIGRATIONS_DIR/$migration_name"
  migration_checksum=$(sha256sum "$migration_file" | awk '{print $1}')

  existing_checksum=$(
    psql_app \
      --tuples-only \
      --no-align \
      --set=ON_ERROR_STOP=1 \
      --set=migration_name="$migration_name" <<'SQL'
SELECT btrim(migration_checksum)
FROM public.migrations
WHERE migration_name = :'migration_name';
SQL
  )

  if [[ -n "$existing_checksum" ]]; then
    if [[ "$existing_checksum" != "$migration_checksum" ]]; then
      echo "[migration] ERROR: '$migration_name' was already applied and its checksum changed." >&2
      echo "[migration] Never edit an applied migration; create a new numbered file." >&2
      exit 1
    fi

    echo "[migration] $migration_name was already applied; skipping it."
    continue
  fi

  echo "[migration] Applying $migration_name..."

  # Apply the SQL and register its checksum in the same transaction.
  {
    printf '%s\n' 'BEGIN;'
    cat "$migration_file"
    cat <<'SQL'

INSERT INTO public.migrations (
    migration_name,
    migration_checksum
) VALUES (
    :'migration_name',
    :'migration_checksum'
);

COMMIT;
SQL
  } | psql_app \
        --set=ON_ERROR_STOP=1 \
        --set=migration_name="$migration_name" \
        --set=migration_checksum="$migration_checksum"

  echo "[migration] $migration_name was applied successfully."
done

echo "[migration] Database schema is up to date."
