CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS audit;

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA core;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA core;

CREATE TABLE audit.revinfo (
    rev bigint GENERATED BY DEFAULT AS IDENTITY,
    revtstmp bigint NOT NULL,
    user_subject varchar(255) NOT NULL,
    username varchar(255) NOT NULL,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE core.configurations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    name text NOT NULL,
    description text,
    value_type varchar(32) NOT NULL,
    configuration_value jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_configurations PRIMARY KEY (id),
    CONSTRAINT uq_configurations_name UNIQUE (name),
    CONSTRAINT ck_configurations_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_configurations_value_type CHECK (value_type IN (
        'STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'DATE', 'DATE_TIME', 'JSON'
    )),
    CONSTRAINT ck_configurations_value_not_null CHECK (configuration_value <> 'null'::jsonb),
    CONSTRAINT ck_configurations_value_matches_type CHECK (
        (value_type IN ('STRING', 'DATE', 'DATE_TIME')
            AND jsonb_typeof(configuration_value) = 'string')
        OR (value_type = 'INTEGER'
            AND jsonb_typeof(configuration_value) = 'number'
            AND mod((configuration_value #>> '{}')::numeric, 1) = 0)
        OR (value_type = 'DECIMAL'
            AND jsonb_typeof(configuration_value) = 'number')
        OR (value_type = 'BOOLEAN'
            AND jsonb_typeof(configuration_value) = 'boolean')
        OR (value_type = 'JSON'
            AND jsonb_typeof(configuration_value) IN ('object', 'array'))
    )
);

CREATE UNIQUE INDEX uq_configurations_name_ci ON core.configurations (lower(name));
CREATE INDEX idx_configurations_value_type ON core.configurations (value_type);

INSERT INTO core.configurations (
    name,
    description,
    value_type,
    configuration_value
) VALUES (
    'KEY_PART',
    'Database component used to derive the key that protects secrets.',
    'STRING',
    to_jsonb(encode(core.gen_random_bytes(32), 'hex'))
);

CREATE TABLE core.tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    scope varchar(32) NOT NULL,
    name text NOT NULL,
    color varchar(7) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT uq_tags_scope_name UNIQUE (scope, name),
    CONSTRAINT uq_tags_id_scope UNIQUE (id, scope),
    CONSTRAINT ck_tags_scope CHECK (scope IN ('CONFIGURATION', 'SECRET')),
    CONSTRAINT ck_tags_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_tags_color CHECK (color ~ '^#[0-9A-F]{6}$')
);

CREATE UNIQUE INDEX uq_tags_scope_name_ci ON core.tags (scope, lower(name));

CREATE TABLE core.configuration_tag (
    configuration_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    tag_scope varchar(32) NOT NULL DEFAULT 'CONFIGURATION',
    CONSTRAINT pk_configuration_tag PRIMARY KEY (configuration_id, tag_id),
    CONSTRAINT ck_configuration_tag_scope CHECK (tag_scope = 'CONFIGURATION'),
    CONSTRAINT fk_configuration_tag_configuration
        FOREIGN KEY (configuration_id) REFERENCES core.configurations (id) ON DELETE CASCADE,
    CONSTRAINT fk_configuration_tag_tag_scope
        FOREIGN KEY (tag_id, tag_scope) REFERENCES core.tags (id, scope) ON DELETE RESTRICT
);

CREATE INDEX idx_configuration_tag_tag ON core.configuration_tag (tag_id, configuration_id);

CREATE TABLE audit.configurations_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    name text,
    description text,
    value_type varchar(32),
    configuration_value jsonb,
    CONSTRAINT pk_configurations_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_configurations_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_configurations_aud_rev ON audit.configurations_aud (rev);

CREATE TABLE audit.tags_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    scope varchar(32),
    name text,
    color varchar(7),
    CONSTRAINT pk_tags_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_tags_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_tags_aud_rev ON audit.tags_aud (rev);

CREATE TABLE audit.configuration_tag_aud (
    configuration_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    CONSTRAINT pk_configuration_tag_aud PRIMARY KEY (configuration_id, tag_id, rev),
    CONSTRAINT fk_configuration_tag_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_configuration_tag_aud_rev ON audit.configuration_tag_aud (rev);
