CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS secrets;

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA core;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA core;

CREATE TABLE audit.revinfo (
    rev bigint GENERATED BY DEFAULT AS IDENTITY,
    revtstmp bigint NOT NULL,
    user_subject varchar(255) NOT NULL,
    username varchar(255) NOT NULL,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE core.configurations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    name text NOT NULL,
    description text,
    value_type varchar(32) NOT NULL,
    configuration_value jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_configurations PRIMARY KEY (id),
    CONSTRAINT uq_configurations_name UNIQUE (name),
    CONSTRAINT ck_configurations_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_configurations_value_type CHECK (value_type IN (
        'STRING', 'EXPRESSION', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'DATE', 'DATE_TIME', 'JSON'
    )),
    CONSTRAINT ck_configurations_value_not_null CHECK (configuration_value <> 'null'::jsonb),
    CONSTRAINT ck_configurations_value_matches_type CHECK (
        (value_type IN ('STRING', 'EXPRESSION', 'DATE', 'DATE_TIME')
            AND jsonb_typeof(configuration_value) = 'string')
        OR (value_type = 'INTEGER'
            AND jsonb_typeof(configuration_value) = 'number'
            AND mod((configuration_value #>> '{}')::numeric, 1) = 0)
        OR (value_type = 'DECIMAL'
            AND jsonb_typeof(configuration_value) = 'number')
        OR (value_type = 'BOOLEAN'
            AND jsonb_typeof(configuration_value) = 'boolean')
        OR (value_type = 'JSON'
            AND jsonb_typeof(configuration_value) IN ('object', 'array'))
    )
);

CREATE UNIQUE INDEX uq_configurations_name_ci ON core.configurations (lower(name));
CREATE INDEX idx_configurations_value_type ON core.configurations (value_type);

INSERT INTO core.configurations (
    name,
    description,
    value_type,
    configuration_value
) VALUES (
    'KEY_PART',
    'Database component used to derive the key that protects secrets.',
    'STRING',
    to_jsonb(encode(core.gen_random_bytes(32), 'hex'))
);

CREATE TABLE core.tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    scope varchar(32) NOT NULL,
    name text NOT NULL,
    color varchar(7) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT uq_tags_scope_name UNIQUE (scope, name),
    CONSTRAINT uq_tags_id_scope UNIQUE (id, scope),
    CONSTRAINT ck_tags_scope CHECK (scope IN ('CONFIGURATION', 'SECRET')),
    CONSTRAINT ck_tags_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_tags_color CHECK (color ~ '^#[0-9A-F]{6}$')
);

CREATE UNIQUE INDEX uq_tags_scope_name_ci ON core.tags (scope, lower(name));

CREATE TABLE core.configuration_tag (
    configuration_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    tag_scope varchar(32) NOT NULL DEFAULT 'CONFIGURATION',
    CONSTRAINT pk_configuration_tag PRIMARY KEY (configuration_id, tag_id),
    CONSTRAINT ck_configuration_tag_scope CHECK (tag_scope = 'CONFIGURATION'),
    CONSTRAINT fk_configuration_tag_configuration
        FOREIGN KEY (configuration_id) REFERENCES core.configurations (id) ON DELETE CASCADE,
    CONSTRAINT fk_configuration_tag_tag_scope
        FOREIGN KEY (tag_id, tag_scope) REFERENCES core.tags (id, scope) ON DELETE RESTRICT
);

CREATE INDEX idx_configuration_tag_tag ON core.configuration_tag (tag_id, configuration_id);

CREATE TABLE core.configuration_expression_dependencies (
    configuration_id bigint NOT NULL,
    referenced_configuration_id bigint NOT NULL,
    CONSTRAINT pk_configuration_expression_dependencies PRIMARY KEY (
        configuration_id, referenced_configuration_id
    ),
    CONSTRAINT fk_configuration_expression_dependencies_configuration
        FOREIGN KEY (configuration_id) REFERENCES core.configurations (id) ON DELETE CASCADE,
    CONSTRAINT fk_configuration_expression_dependencies_referenced_configuration
        FOREIGN KEY (referenced_configuration_id) REFERENCES core.configurations (id) ON DELETE RESTRICT
);

CREATE INDEX idx_configuration_expression_dependencies_referenced
    ON core.configuration_expression_dependencies (referenced_configuration_id, configuration_id);

CREATE TABLE audit.configurations_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    name text,
    description text,
    value_type varchar(32),
    configuration_value jsonb,
    CONSTRAINT pk_configurations_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_configurations_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_configurations_aud_rev ON audit.configurations_aud (rev);

CREATE TABLE audit.tags_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    scope varchar(32),
    name text,
    color varchar(7),
    CONSTRAINT pk_tags_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_tags_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_tags_aud_rev ON audit.tags_aud (rev);

CREATE TABLE audit.configuration_tag_aud (
    configuration_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    CONSTRAINT pk_configuration_tag_aud PRIMARY KEY (configuration_id, tag_id, rev),
    CONSTRAINT fk_configuration_tag_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_configuration_tag_aud_rev ON audit.configuration_tag_aud (rev);

CREATE TABLE secrets.secrets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    name text NOT NULL,
    description text,
    encrypted_value bytea NOT NULL,
    encryption_iv bytea NOT NULL,
    value_hash bytea NOT NULL,
    hash_salt bytea NOT NULL,
    encryption_version smallint NOT NULL,
    value_revision bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_secrets PRIMARY KEY (id),
    CONSTRAINT uq_secrets_name UNIQUE (name),
    CONSTRAINT ck_secrets_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_secrets_encrypted_value_length CHECK (octet_length(encrypted_value) >= 16),
    CONSTRAINT ck_secrets_encryption_iv_length CHECK (octet_length(encryption_iv) = 12),
    CONSTRAINT ck_secrets_value_hash_length CHECK (octet_length(value_hash) = 32),
    CONSTRAINT ck_secrets_hash_salt_length CHECK (octet_length(hash_salt) = 16),
    CONSTRAINT ck_secrets_encryption_version CHECK (encryption_version > 0),
    CONSTRAINT ck_secrets_value_revision CHECK (value_revision > 0)
);

CREATE UNIQUE INDEX uq_secrets_name_ci ON secrets.secrets (lower(name));

CREATE TABLE secrets.secret_tag (
    secret_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    tag_scope varchar(32) NOT NULL DEFAULT 'SECRET',
    CONSTRAINT pk_secret_tag PRIMARY KEY (secret_id, tag_id),
    CONSTRAINT ck_secret_tag_scope CHECK (tag_scope = 'SECRET'),
    CONSTRAINT fk_secret_tag_secret
        FOREIGN KEY (secret_id) REFERENCES secrets.secrets (id) ON DELETE CASCADE,
    CONSTRAINT fk_secret_tag_tag_scope
        FOREIGN KEY (tag_id, tag_scope) REFERENCES core.tags (id, scope) ON DELETE RESTRICT
);

CREATE INDEX idx_secret_tag_tag ON secrets.secret_tag (tag_id, secret_id);

CREATE TABLE audit.secrets_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    name text,
    description text,
    encryption_version smallint,
    value_revision bigint,
    CONSTRAINT pk_secrets_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_secrets_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_secrets_aud_rev ON audit.secrets_aud (rev);

CREATE TABLE audit.secret_tag_aud (
    secret_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    CONSTRAINT pk_secret_tag_aud PRIMARY KEY (secret_id, tag_id, rev),
    CONSTRAINT fk_secret_tag_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_secret_tag_aud_rev ON audit.secret_tag_aud (rev);

CREATE TABLE audit.log_levels (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(32) NOT NULL,
    CONSTRAINT pk_log_levels PRIMARY KEY (id),
    CONSTRAINT uq_log_levels_code UNIQUE (code),
    CONSTRAINT ck_log_levels_code_not_blank CHECK (btrim(code) <> '')
);

CREATE TABLE audit.log_sources (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(128) NOT NULL,
    CONSTRAINT pk_log_sources PRIMARY KEY (id),
    CONSTRAINT uq_log_sources_code UNIQUE (code),
    CONSTRAINT ck_log_sources_code_not_blank CHECK (btrim(code) <> '')
);

CREATE TABLE audit.log_events (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(128) NOT NULL,
    CONSTRAINT pk_log_events PRIMARY KEY (id),
    CONSTRAINT uq_log_events_code UNIQUE (code),
    CONSTRAINT ck_log_events_code_not_blank CHECK (btrim(code) <> '')
);

INSERT INTO audit.log_levels (code) VALUES
    ('INFO'),
    ('WARN'),
    ('ERROR');

INSERT INTO audit.log_sources (code) VALUES
    ('alertify-backend');

INSERT INTO audit.log_events (code) VALUES
    ('ALERT_BINDING_CATALOG_ACCESSED'),
    ('ALERT_CREATED'),
    ('ALERT_DELETED'),
    ('ALERT_EXECUTION_HISTORY_VIEWED'),
    ('ALERT_PAGE_VIEWED'),
    ('ALERT_TEMPLATE_CATALOG_VIEWED'),
    ('ALERT_UPDATED'),
    ('API_ERROR_SHOWN'),
    ('API_REQUEST'),
    ('API_UNHANDLED_ERROR'),
    ('CONFIGURATION_CREATED'),
    ('CONFIGURATION_DELETED'),
    ('CONFIGURATION_PAGE_VIEWED'),
    ('CONFIGURATION_TAG_CREATED'),
    ('CONFIGURATION_TAG_DELETED'),
    ('CONFIGURATION_TAG_UPDATED'),
    ('CONFIGURATION_UPDATED'),
    ('CONFIGURATION_VIEWED'),
    ('CONFIGURATION_EXPRESSION_EVALUATED'),
    ('SECRET_CATALOG_ACCESSED'),
    ('SECRET_CREATED'),
    ('SECRET_DELETED'),
    ('SECRET_PAGE_VIEWED'),
    ('SECRET_TAG_CREATED'),
    ('SECRET_TAG_DELETED'),
    ('SECRET_TAG_UPDATED'),
    ('SECRET_UPDATED'),
    ('SECRET_VALUE_ACCESSED'),
    ('SECRET_VIEWED'),
    ('USER_LOGIN'),
    ('USER_LOGOUT'),
    ('WORKER_DNS_RESOLUTION_FAILED'),
    ('WORKER_DNS_RESOLUTION_RECOVERED'),
    ('WORKER_IP_AVAILABLE'),
    ('WORKER_IP_DISCOVERED'),
    ('WORKER_IP_REMOVED'),
    ('WORKER_IP_UNAVAILABLE');

CREATE TABLE audit.logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    level_id smallint NOT NULL,
    source_id smallint NOT NULL,
    event_id smallint NOT NULL,
    outcome varchar(16) NOT NULL,
    user_subject text NOT NULL,
    username text NOT NULL,
    request_id uuid,
    path text,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_logs PRIMARY KEY (id),
    CONSTRAINT ck_logs_outcome CHECK (outcome IN ('SUCCESS', 'FAILURE')),
    CONSTRAINT ck_logs_user_subject_not_blank CHECK (btrim(user_subject) <> ''),
    CONSTRAINT ck_logs_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT ck_logs_data_object CHECK (jsonb_typeof(data) = 'object'),
    CONSTRAINT fk_logs_level FOREIGN KEY (level_id) REFERENCES audit.log_levels (id),
    CONSTRAINT fk_logs_source FOREIGN KEY (source_id) REFERENCES audit.log_sources (id),
    CONSTRAINT fk_logs_event FOREIGN KEY (event_id) REFERENCES audit.log_events (id)
);

CREATE INDEX idx_logs_username ON audit.logs (username);
CREATE INDEX idx_logs_user_subject ON audit.logs (user_subject);
CREATE INDEX idx_logs_event_at ON audit.logs (event_at DESC);
CREATE INDEX idx_logs_path ON audit.logs (path);
CREATE INDEX idx_logs_level_id ON audit.logs (level_id);
CREATE INDEX idx_logs_source_id ON audit.logs (source_id);
CREATE INDEX idx_logs_event_id ON audit.logs (event_id);

CREATE TABLE core.alert_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    template_key text NOT NULL,
    name_key text NOT NULL,
    description_key text NOT NULL,
    required_capability varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_alert_templates PRIMARY KEY (id),
    CONSTRAINT uq_alert_templates_template_key UNIQUE (template_key),
    CONSTRAINT ck_alert_templates_template_key_trimmed CHECK (
        template_key = btrim(template_key) AND template_key <> ''
    ),
    CONSTRAINT ck_alert_templates_name_key_trimmed CHECK (
        name_key = btrim(name_key) AND name_key <> ''
    ),
    CONSTRAINT ck_alert_templates_description_key_trimmed CHECK (
        description_key = btrim(description_key) AND description_key <> ''
    ),
    CONSTRAINT ck_alert_templates_required_capability CHECK (
        required_capability IN ('STANDARD', 'PLAYWRIGHT')
    )
);

CREATE INDEX idx_alert_templates_required_capability
    ON core.alert_templates (required_capability);

CREATE TABLE core.alert_template_parameters (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    alert_template_id bigint NOT NULL,
    parameter_key text NOT NULL,
    label_key text NOT NULL,
    description_key text NOT NULL,
    java_type text NOT NULL,
    options jsonb NOT NULL DEFAULT '[]'::jsonb,
    binding_allowed boolean NOT NULL,
    default_value text,
    parameter_order integer NOT NULL,
    required boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_alert_template_parameters PRIMARY KEY (id),
    CONSTRAINT uq_alert_template_parameters_template_key UNIQUE (
        alert_template_id, parameter_key
    ),
    CONSTRAINT ck_alert_template_parameters_key_trimmed CHECK (
        parameter_key = btrim(parameter_key) AND parameter_key <> ''
    ),
    CONSTRAINT ck_alert_template_parameters_label_key_trimmed CHECK (
        label_key = btrim(label_key) AND label_key <> ''
    ),
    CONSTRAINT ck_alert_template_parameters_description_key_trimmed CHECK (
        description_key = btrim(description_key) AND description_key <> ''
    ),
    CONSTRAINT ck_alert_template_parameters_java_type_trimmed CHECK (
        java_type = btrim(java_type) AND java_type <> ''
    ),
    CONSTRAINT ck_alert_template_parameters_options CHECK (
        jsonb_typeof(options) = 'array'
    ),
    CONSTRAINT ck_alert_template_parameters_nonbinding_options CHECK (
        binding_allowed OR jsonb_array_length(options) > 0
    ),
    CONSTRAINT ck_alert_template_parameters_nonbinding_default CHECK (
        default_value IS NULL
        OR binding_allowed
        OR options ? default_value
    ),
    CONSTRAINT ck_alert_template_parameters_order CHECK (parameter_order >= 0),
    CONSTRAINT fk_alert_template_parameters_template FOREIGN KEY (alert_template_id)
        REFERENCES core.alert_templates (id) ON DELETE RESTRICT
);

CREATE INDEX idx_alert_template_parameters_template_order
    ON core.alert_template_parameters (alert_template_id, parameter_order, id);

CREATE TABLE core.alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    alert_template_id bigint NOT NULL,
    name text NOT NULL,
    description text,
    cron_expression text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    state text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_alerts PRIMARY KEY (id),
    CONSTRAINT uq_alerts_name UNIQUE (name),
    CONSTRAINT ck_alerts_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_alerts_cron_expression_trimmed CHECK (
        cron_expression = btrim(cron_expression) AND cron_expression <> ''
    ),
    CONSTRAINT fk_alerts_template FOREIGN KEY (alert_template_id)
        REFERENCES core.alert_templates (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_alerts_name_ci ON core.alerts (lower(name));
CREATE INDEX idx_alerts_template ON core.alerts (alert_template_id);
CREATE INDEX idx_alerts_enabled ON core.alerts (enabled) WHERE enabled;

CREATE TABLE core.alert_parameter_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    alert_id bigint NOT NULL,
    template_parameter_id bigint NOT NULL,
    source varchar(32) NOT NULL,
    text_value text,
    configuration_id bigint,
    secret_id bigint,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_alert_parameter_values PRIMARY KEY (id),
    CONSTRAINT uq_alert_parameter_values_alert_parameter UNIQUE (
        alert_id, template_parameter_id
    ),
    CONSTRAINT ck_alert_parameter_values_source CHECK (
        source IN ('TEXT', 'CONFIGURATION', 'SECRET')
    ),
    CONSTRAINT ck_alert_parameter_values_selected_source CHECK (
        (source = 'TEXT'
            AND text_value IS NOT NULL
            AND configuration_id IS NULL
            AND secret_id IS NULL)
        OR (source = 'CONFIGURATION'
            AND text_value IS NULL
            AND configuration_id IS NOT NULL
            AND secret_id IS NULL)
        OR (source = 'SECRET'
            AND text_value IS NULL
            AND configuration_id IS NULL
            AND secret_id IS NOT NULL)
    ),
    CONSTRAINT fk_alert_parameter_values_alert FOREIGN KEY (alert_id)
        REFERENCES core.alerts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_alert_parameter_values_template_parameter FOREIGN KEY (template_parameter_id)
        REFERENCES core.alert_template_parameters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_alert_parameter_values_configuration FOREIGN KEY (configuration_id)
        REFERENCES core.configurations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_alert_parameter_values_secret FOREIGN KEY (secret_id)
        REFERENCES secrets.secrets (id) ON DELETE RESTRICT
);

CREATE INDEX idx_alert_parameter_values_template_parameter
    ON core.alert_parameter_values (template_parameter_id);
CREATE INDEX idx_alert_parameter_values_configuration
    ON core.alert_parameter_values (configuration_id) WHERE configuration_id IS NOT NULL;
CREATE INDEX idx_alert_parameter_values_secret
    ON core.alert_parameter_values (secret_id) WHERE secret_id IS NOT NULL;

CREATE TABLE core.alert_executions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    alert_id bigint NOT NULL,
    status varchar(16) NOT NULL,
    started_at timestamptz NOT NULL,
    finished_at timestamptz NOT NULL,
    status_message jsonb,
    error_type text,
    error_message text,
    error_stack_trace text,
    CONSTRAINT pk_alert_executions PRIMARY KEY (id),
    CONSTRAINT ck_alert_executions_status CHECK (status IN ('SUCCESS', 'WARN', 'ERROR')),
    CONSTRAINT ck_alert_executions_time CHECK (finished_at >= started_at),
    CONSTRAINT ck_alert_executions_error_fields CHECK (
        (status IN ('SUCCESS', 'WARN')
            AND error_type IS NULL
            AND error_message IS NULL
            AND error_stack_trace IS NULL)
        OR (status = 'ERROR' AND error_type IS NOT NULL AND btrim(error_type) <> '')
    ),
    CONSTRAINT fk_alert_executions_alert FOREIGN KEY (alert_id)
        REFERENCES core.alerts (id) ON DELETE RESTRICT
);

CREATE INDEX idx_alert_executions_alert_started
    ON core.alert_executions (alert_id, started_at DESC);
CREATE INDEX idx_alert_executions_status_started
    ON core.alert_executions (status, started_at DESC);

CREATE TABLE audit.alert_templates_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    template_key text,
    name_key text,
    description_key text,
    required_capability varchar(32),
    CONSTRAINT pk_alert_templates_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_alert_templates_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_alert_templates_aud_rev ON audit.alert_templates_aud (rev);

CREATE TABLE audit.alert_template_parameters_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    alert_template_id bigint,
    parameter_key text,
    label_key text,
    description_key text,
    java_type text,
    options jsonb,
    binding_allowed boolean,
    default_value text,
    parameter_order integer,
    required boolean,
    CONSTRAINT pk_alert_template_parameters_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_alert_template_parameters_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_alert_template_parameters_aud_rev
    ON audit.alert_template_parameters_aud (rev);

CREATE TABLE audit.alerts_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    alert_template_id bigint,
    name text,
    description text,
    cron_expression text,
    enabled boolean,
    CONSTRAINT pk_alerts_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_alerts_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_alerts_aud_rev ON audit.alerts_aud (rev);

CREATE TABLE audit.alert_parameter_values_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    alert_id bigint,
    template_parameter_id bigint,
    source varchar(32),
    text_value text,
    configuration_id bigint,
    secret_id bigint,
    CONSTRAINT pk_alert_parameter_values_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_alert_parameter_values_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_alert_parameter_values_aud_rev
    ON audit.alert_parameter_values_aud (rev);
