ALTER TABLE core.tags
    DROP CONSTRAINT ck_tags_scope;

ALTER TABLE core.tags
    ADD CONSTRAINT ck_tags_scope CHECK (
        scope IN ('CONFIGURATION', 'SECRET', 'ALERT', 'PROCEDURE')
    );

CREATE TABLE core.procedure_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    template_key text NOT NULL,
    name_key text NOT NULL,
    description_key text NOT NULL,
    source_path text NOT NULL,
    required_capability varchar(32) NOT NULL,
    sensitive_result boolean NOT NULL DEFAULT false,
    tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_procedure_templates PRIMARY KEY (id),
    CONSTRAINT uq_procedure_templates_template_key UNIQUE (template_key),
    CONSTRAINT ck_procedure_templates_template_key_trimmed CHECK (
        template_key = btrim(template_key) AND template_key <> ''
    ),
    CONSTRAINT ck_procedure_templates_name_key_trimmed CHECK (
        name_key = btrim(name_key) AND name_key <> ''
    ),
    CONSTRAINT ck_procedure_templates_description_key_trimmed CHECK (
        description_key = btrim(description_key) AND description_key <> ''
    ),
    CONSTRAINT ck_procedure_templates_source_path_trimmed CHECK (
        source_path = btrim(source_path) AND source_path <> ''
    ),
    CONSTRAINT ck_procedure_templates_required_capability CHECK (
        required_capability IN ('STANDARD', 'PLAYWRIGHT')
    ),
    CONSTRAINT ck_procedure_templates_tags_array CHECK (jsonb_typeof(tags) = 'array')
);

CREATE INDEX idx_procedure_templates_required_capability
    ON core.procedure_templates (required_capability);

CREATE TABLE core.procedure_template_parameters (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    procedure_template_id bigint NOT NULL,
    parameter_key text NOT NULL,
    label_key text NOT NULL,
    description_key text NOT NULL,
    java_type text NOT NULL,
    options jsonb NOT NULL DEFAULT '[]'::jsonb,
    binding_allowed boolean NOT NULL,
    default_value text,
    multiline boolean NOT NULL DEFAULT false,
    parameter_order integer NOT NULL,
    required boolean NOT NULL,
    allowed_sources jsonb NOT NULL DEFAULT '["TEXT","CONFIGURATION","SECRET"]'::jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_procedure_template_parameters PRIMARY KEY (id),
    CONSTRAINT uq_procedure_template_parameters_template_key UNIQUE (
        procedure_template_id, parameter_key
    ),
    CONSTRAINT ck_procedure_template_parameters_key_trimmed CHECK (
        parameter_key = btrim(parameter_key) AND parameter_key <> ''
    ),
    CONSTRAINT ck_procedure_template_parameters_label_key_trimmed CHECK (
        label_key = btrim(label_key) AND label_key <> ''
    ),
    CONSTRAINT ck_procedure_template_parameters_description_key_trimmed CHECK (
        description_key = btrim(description_key) AND description_key <> ''
    ),
    CONSTRAINT ck_procedure_template_parameters_java_type_trimmed CHECK (
        java_type = btrim(java_type) AND java_type <> ''
    ),
    CONSTRAINT ck_procedure_template_parameters_options CHECK (
        jsonb_typeof(options) = 'array'
    ),
    CONSTRAINT ck_procedure_template_parameters_allowed_sources CHECK (
        jsonb_typeof(allowed_sources) = 'array' AND jsonb_array_length(allowed_sources) > 0
    ),
    CONSTRAINT ck_procedure_template_parameters_nonbinding_options CHECK (
        binding_allowed OR jsonb_array_length(options) > 0
    ),
    CONSTRAINT ck_procedure_template_parameters_nonbinding_default CHECK (
        default_value IS NULL OR binding_allowed OR options ? default_value
    ),
    CONSTRAINT ck_procedure_template_parameters_order CHECK (parameter_order >= 0),
    CONSTRAINT fk_procedure_template_parameters_template
        FOREIGN KEY (procedure_template_id)
        REFERENCES core.procedure_templates (id) ON DELETE RESTRICT
);

CREATE INDEX idx_procedure_template_parameters_template_order
    ON core.procedure_template_parameters (procedure_template_id, parameter_order, id);

CREATE TABLE core.procedures (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    procedure_template_id bigint NOT NULL,
    name text NOT NULL,
    description text,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_procedures PRIMARY KEY (id),
    CONSTRAINT uq_procedures_name UNIQUE (name),
    CONSTRAINT ck_procedures_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT fk_procedures_template FOREIGN KEY (procedure_template_id)
        REFERENCES core.procedure_templates (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_procedures_name_ci ON core.procedures (lower(name));
CREATE INDEX idx_procedures_template ON core.procedures (procedure_template_id);
CREATE INDEX idx_procedures_enabled ON core.procedures (enabled) WHERE enabled;

CREATE TABLE core.procedure_tag (
    procedure_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    tag_scope varchar(32) NOT NULL DEFAULT 'PROCEDURE',
    CONSTRAINT pk_procedure_tag PRIMARY KEY (procedure_id, tag_id),
    CONSTRAINT ck_procedure_tag_scope CHECK (tag_scope = 'PROCEDURE'),
    CONSTRAINT fk_procedure_tag_procedure
        FOREIGN KEY (procedure_id) REFERENCES core.procedures (id) ON DELETE CASCADE,
    CONSTRAINT fk_procedure_tag_tag_scope
        FOREIGN KEY (tag_id, tag_scope) REFERENCES core.tags (id, scope) ON DELETE RESTRICT
);

CREATE INDEX idx_procedure_tag_tag ON core.procedure_tag (tag_id, procedure_id);

CREATE TABLE core.procedure_parameter_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    owner_procedure_id bigint NOT NULL,
    template_parameter_id bigint NOT NULL,
    source varchar(32) NOT NULL,
    text_value text,
    configuration_id bigint,
    secret_id bigint,
    referenced_procedure_id bigint,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_procedure_parameter_values PRIMARY KEY (id),
    CONSTRAINT uq_procedure_parameter_values_owner_parameter UNIQUE (
        owner_procedure_id, template_parameter_id
    ),
    CONSTRAINT ck_procedure_parameter_values_source CHECK (
        source IN ('TEXT', 'CONFIGURATION', 'SECRET', 'PROCEDURE')
    ),
    CONSTRAINT ck_procedure_parameter_values_selected_source CHECK (
        (source = 'TEXT' AND text_value IS NOT NULL AND configuration_id IS NULL
            AND secret_id IS NULL AND referenced_procedure_id IS NULL)
        OR (source = 'CONFIGURATION' AND text_value IS NULL AND configuration_id IS NOT NULL
            AND secret_id IS NULL AND referenced_procedure_id IS NULL)
        OR (source = 'SECRET' AND text_value IS NULL AND configuration_id IS NULL
            AND secret_id IS NOT NULL AND referenced_procedure_id IS NULL)
        OR (source = 'PROCEDURE' AND text_value IS NULL AND configuration_id IS NULL
            AND secret_id IS NULL AND referenced_procedure_id IS NOT NULL)
    ),
    CONSTRAINT fk_procedure_parameter_values_owner FOREIGN KEY (owner_procedure_id)
        REFERENCES core.procedures (id) ON DELETE RESTRICT,
    CONSTRAINT fk_procedure_parameter_values_template_parameter FOREIGN KEY (template_parameter_id)
        REFERENCES core.procedure_template_parameters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_procedure_parameter_values_configuration FOREIGN KEY (configuration_id)
        REFERENCES core.configurations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_procedure_parameter_values_secret FOREIGN KEY (secret_id)
        REFERENCES secrets.secrets (id) ON DELETE RESTRICT,
    CONSTRAINT fk_procedure_parameter_values_referenced_procedure FOREIGN KEY (referenced_procedure_id)
        REFERENCES core.procedures (id) ON DELETE RESTRICT
);

CREATE INDEX idx_procedure_parameter_values_template_parameter
    ON core.procedure_parameter_values (template_parameter_id);
CREATE INDEX idx_procedure_parameter_values_configuration
    ON core.procedure_parameter_values (configuration_id) WHERE configuration_id IS NOT NULL;
CREATE INDEX idx_procedure_parameter_values_secret
    ON core.procedure_parameter_values (secret_id) WHERE secret_id IS NOT NULL;
CREATE INDEX idx_procedure_parameter_values_referenced
    ON core.procedure_parameter_values (referenced_procedure_id)
    WHERE referenced_procedure_id IS NOT NULL;

ALTER TABLE core.alert_parameter_values
    ADD COLUMN procedure_id bigint;

ALTER TABLE core.alert_parameter_values
    DROP CONSTRAINT ck_alert_parameter_values_source,
    DROP CONSTRAINT ck_alert_parameter_values_selected_source;

ALTER TABLE core.alert_parameter_values
    ADD CONSTRAINT ck_alert_parameter_values_source CHECK (
        source IN ('TEXT', 'CONFIGURATION', 'SECRET', 'PROCEDURE')
    ),
    ADD CONSTRAINT ck_alert_parameter_values_selected_source CHECK (
        (source = 'TEXT' AND text_value IS NOT NULL AND configuration_id IS NULL
            AND secret_id IS NULL AND procedure_id IS NULL)
        OR (source = 'CONFIGURATION' AND text_value IS NULL AND configuration_id IS NOT NULL
            AND secret_id IS NULL AND procedure_id IS NULL)
        OR (source = 'SECRET' AND text_value IS NULL AND configuration_id IS NULL
            AND secret_id IS NOT NULL AND procedure_id IS NULL)
        OR (source = 'PROCEDURE' AND text_value IS NULL AND configuration_id IS NULL
            AND secret_id IS NULL AND procedure_id IS NOT NULL)
    ),
    ADD CONSTRAINT fk_alert_parameter_values_procedure FOREIGN KEY (procedure_id)
        REFERENCES core.procedures (id) ON DELETE RESTRICT;

CREATE INDEX idx_alert_parameter_values_procedure
    ON core.alert_parameter_values (procedure_id) WHERE procedure_id IS NOT NULL;

CREATE TABLE core.procedure_executions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    execution_id uuid NOT NULL,
    procedure_id bigint NOT NULL,
    procedure_version bigint NOT NULL,
    status varchar(16) NOT NULL,
    trigger varchar(16) NOT NULL,
    root_execution_id uuid NOT NULL,
    parent_alert_execution_id uuid,
    parent_procedure_execution_id uuid,
    depth integer NOT NULL,
    started_at timestamptz NOT NULL,
    work_started_at timestamptz,
    finished_at timestamptz,
    result_json jsonb,
    result_redacted boolean NOT NULL DEFAULT false,
    error_type text,
    error_message text,
    error_stack_trace text,
    worker_name text,
    worker_ip_address varchar(45),
    worker_port integer,
    worker_instance_id uuid,
    triggered_by text,
    CONSTRAINT pk_procedure_executions PRIMARY KEY (id),
    CONSTRAINT uq_procedure_executions_execution_id UNIQUE (execution_id),
    CONSTRAINT ck_procedure_executions_status CHECK (
        status IN ('RUNNING', 'COMPLETED', 'ERROR')
    ),
    CONSTRAINT ck_procedure_executions_trigger CHECK (
        trigger IN ('MANUAL', 'ALERT', 'PROCEDURE')
    ),
    CONSTRAINT ck_procedure_executions_depth CHECK (depth BETWEEN 1 AND 16),
    CONSTRAINT ck_procedure_executions_parent CHECK (
        (trigger = 'MANUAL' AND parent_alert_execution_id IS NULL
            AND parent_procedure_execution_id IS NULL AND depth = 1)
        OR (trigger = 'ALERT' AND parent_alert_execution_id IS NOT NULL
            AND parent_procedure_execution_id IS NULL)
        OR (trigger = 'PROCEDURE' AND parent_alert_execution_id IS NULL
            AND parent_procedure_execution_id IS NOT NULL)
    ),
    CONSTRAINT ck_procedure_executions_time CHECK (
        work_started_at IS NULL OR work_started_at >= started_at
    ),
    CONSTRAINT ck_procedure_executions_finished_time CHECK (
        finished_at IS NULL OR (work_started_at IS NOT NULL AND finished_at >= work_started_at)
    ),
    CONSTRAINT ck_procedure_executions_outcome CHECK (
        (status = 'RUNNING' AND finished_at IS NULL AND result_json IS NULL
            AND NOT result_redacted AND error_type IS NULL AND error_message IS NULL
            AND error_stack_trace IS NULL)
        OR (status = 'COMPLETED' AND finished_at IS NOT NULL
            AND (result_json IS NOT NULL OR result_redacted)
            AND error_type IS NULL AND error_message IS NULL AND error_stack_trace IS NULL)
        OR (status = 'ERROR' AND finished_at IS NOT NULL AND result_json IS NULL
            AND NOT result_redacted AND error_type IS NOT NULL AND btrim(error_type) <> '')
    ),
    CONSTRAINT ck_procedure_executions_worker_port CHECK (
        worker_port IS NULL OR worker_port BETWEEN 1 AND 65535
    ),
    CONSTRAINT ck_procedure_executions_worker_identity CHECK (
        (worker_name IS NULL AND worker_ip_address IS NULL AND worker_port IS NULL
            AND worker_instance_id IS NULL)
        OR (worker_name IS NOT NULL AND worker_ip_address IS NOT NULL
            AND worker_port IS NOT NULL AND worker_instance_id IS NOT NULL)
    ),
    CONSTRAINT fk_procedure_executions_procedure FOREIGN KEY (procedure_id)
        REFERENCES core.procedures (id) ON DELETE RESTRICT
);

CREATE INDEX idx_procedure_executions_procedure_started
    ON core.procedure_executions (procedure_id, started_at DESC);
CREATE INDEX idx_procedure_executions_status_started
    ON core.procedure_executions (status, started_at DESC);
CREATE INDEX idx_procedure_executions_root
    ON core.procedure_executions (root_execution_id, started_at);
CREATE INDEX idx_procedure_executions_parent_alert
    ON core.procedure_executions (parent_alert_execution_id)
    WHERE parent_alert_execution_id IS NOT NULL;
CREATE INDEX idx_procedure_executions_parent_procedure
    ON core.procedure_executions (parent_procedure_execution_id)
    WHERE parent_procedure_execution_id IS NOT NULL;

CREATE TABLE audit.procedure_templates_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    template_key text,
    name_key text,
    description_key text,
    source_path text,
    required_capability varchar(32),
    sensitive_result boolean,
    tags jsonb,
    CONSTRAINT pk_procedure_templates_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_procedure_templates_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE TABLE audit.procedure_template_parameters_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    procedure_template_id bigint,
    parameter_key text,
    label_key text,
    description_key text,
    java_type text,
    options jsonb,
    binding_allowed boolean,
    default_value text,
    multiline boolean,
    parameter_order integer,
    required boolean,
    allowed_sources jsonb,
    CONSTRAINT pk_procedure_template_parameters_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_procedure_template_parameters_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE TABLE audit.procedures_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    procedure_template_id bigint,
    name text,
    description text,
    enabled boolean,
    CONSTRAINT pk_procedures_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_procedures_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE TABLE audit.procedure_parameter_values_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    owner_procedure_id bigint,
    template_parameter_id bigint,
    source varchar(32),
    text_value text,
    configuration_id bigint,
    secret_id bigint,
    referenced_procedure_id bigint,
    CONSTRAINT pk_procedure_parameter_values_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_procedure_parameter_values_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE TABLE audit.procedure_tag_aud (
    procedure_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    CONSTRAINT pk_procedure_tag_aud PRIMARY KEY (procedure_id, tag_id, rev),
    CONSTRAINT fk_procedure_tag_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

ALTER TABLE audit.alert_parameter_values_aud
    ADD COLUMN procedure_id bigint;

CREATE INDEX idx_procedure_templates_aud_rev ON audit.procedure_templates_aud (rev);
CREATE INDEX idx_procedure_template_parameters_aud_rev ON audit.procedure_template_parameters_aud (rev);
CREATE INDEX idx_procedures_aud_rev ON audit.procedures_aud (rev);
CREATE INDEX idx_procedure_parameter_values_aud_rev ON audit.procedure_parameter_values_aud (rev);
CREATE INDEX idx_procedure_tag_aud_rev ON audit.procedure_tag_aud (rev);

INSERT INTO audit.log_events (code) VALUES
    ('PROCEDURE_TEMPLATE_CATALOG_VIEWED'),
    ('PROCEDURE_CREATED'),
    ('PROCEDURE_UPDATED'),
    ('PROCEDURE_DELETED'),
    ('PROCEDURE_PAGE_VIEWED'),
    ('PROCEDURE_EXECUTION_TRIGGERED'),
    ('PROCEDURE_EXECUTION_STARTED'),
    ('PROCEDURE_EXECUTION_COMPLETED'),
    ('PROCEDURE_EXECUTION_REJECTED'),
    ('PROCEDURE_EXECUTION_HISTORY_VIEWED'),
    ('PROCEDURE_BINDING_CATALOG_ACCESSED'),
    ('PROCEDURE_TAG_CREATED'),
    ('PROCEDURE_TAG_UPDATED'),
    ('PROCEDURE_TAG_DELETED'),
    ('CONFIGURATION_OVERWRITTEN_BY_PROCEDURE'),
    ('SECRET_OVERWRITTEN_BY_PROCEDURE');
