ALTER TABLE core.alert_executions
    ADD COLUMN trigger varchar(16),
    ADD COLUMN triggered_by text,
    ADD CONSTRAINT ck_alert_executions_trigger CHECK (
        trigger IS NULL OR trigger IN ('CRON', 'MANUAL', 'HOOK')
    );

ALTER TABLE core.procedure_executions
    DROP CONSTRAINT ck_procedure_executions_trigger,
    DROP CONSTRAINT ck_procedure_executions_parent,
    ADD CONSTRAINT ck_procedure_executions_trigger CHECK (
        trigger IN ('MANUAL', 'ALERT', 'PROCEDURE', 'HOOK')
    ),
    ADD CONSTRAINT ck_procedure_executions_parent CHECK (
        (trigger IN ('MANUAL', 'HOOK') AND parent_alert_execution_id IS NULL
            AND parent_procedure_execution_id IS NULL AND depth = 1)
        OR (trigger = 'ALERT' AND parent_alert_execution_id IS NOT NULL
            AND parent_procedure_execution_id IS NULL)
        OR (trigger = 'PROCEDURE' AND parent_alert_execution_id IS NULL
            AND parent_procedure_execution_id IS NOT NULL)
    );

CREATE TABLE core.hooks (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    public_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    enabled boolean NOT NULL DEFAULT false,
    mode varchar(16) NOT NULL,
    token_secret_id bigint,
    max_concurrent_invocations integer,
    rate_limit_count integer,
    rate_limit_window_seconds bigint,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_hooks PRIMARY KEY (id),
    CONSTRAINT uq_hooks_public_id UNIQUE (public_id),
    CONSTRAINT uq_hooks_name UNIQUE (name),
    CONSTRAINT ck_hooks_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_hooks_mode CHECK (mode IN ('PARALLEL', 'SEQUENTIAL')),
    CONSTRAINT ck_hooks_max_concurrent CHECK (
        max_concurrent_invocations IS NULL OR max_concurrent_invocations > 0
    ),
    CONSTRAINT ck_hooks_rate_limit CHECK (
        (rate_limit_count IS NULL AND rate_limit_window_seconds IS NULL)
        OR (rate_limit_count > 0 AND rate_limit_window_seconds > 0)
    ),
    CONSTRAINT fk_hooks_token_secret FOREIGN KEY (token_secret_id)
        REFERENCES secrets.secrets (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_hooks_name_ci ON core.hooks (lower(name));
CREATE INDEX idx_hooks_enabled ON core.hooks (enabled) WHERE enabled;
CREATE INDEX idx_hooks_token_secret ON core.hooks (token_secret_id) WHERE token_secret_id IS NOT NULL;

CREATE TABLE core.hook_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    hook_id bigint NOT NULL,
    target_type varchar(16) NOT NULL,
    alert_id bigint,
    procedure_id bigint,
    position integer NOT NULL,
    continue_on jsonb NOT NULL DEFAULT '["SUCCESS"]'::jsonb,
    busy_wait_timeout_millis bigint,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_hook_targets PRIMARY KEY (id),
    CONSTRAINT uq_hook_targets_position UNIQUE (hook_id, position),
    CONSTRAINT uq_hook_targets_alert UNIQUE (hook_id, alert_id),
    CONSTRAINT uq_hook_targets_procedure UNIQUE (hook_id, procedure_id),
    CONSTRAINT ck_hook_targets_type CHECK (target_type IN ('ALERT', 'PROCEDURE')),
    CONSTRAINT ck_hook_targets_resource CHECK (
        (target_type = 'ALERT' AND alert_id IS NOT NULL AND procedure_id IS NULL)
        OR (target_type = 'PROCEDURE' AND alert_id IS NULL AND procedure_id IS NOT NULL)
    ),
    CONSTRAINT ck_hook_targets_position CHECK (position >= 0),
    CONSTRAINT ck_hook_targets_continue_on CHECK (
        jsonb_typeof(continue_on) = 'array'
        AND continue_on <@ '["SUCCESS","WARN","ERROR"]'::jsonb
    ),
    CONSTRAINT ck_hook_targets_busy_wait CHECK (
        (target_type = 'ALERT' AND busy_wait_timeout_millis > 0)
        OR (target_type = 'PROCEDURE' AND busy_wait_timeout_millis IS NULL)
    ),
    CONSTRAINT fk_hook_targets_hook FOREIGN KEY (hook_id)
        REFERENCES core.hooks (id) ON DELETE CASCADE,
    CONSTRAINT fk_hook_targets_alert FOREIGN KEY (alert_id)
        REFERENCES core.alerts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_hook_targets_procedure FOREIGN KEY (procedure_id)
        REFERENCES core.procedures (id) ON DELETE RESTRICT
);

CREATE INDEX idx_hook_targets_hook_position ON core.hook_targets (hook_id, position);
CREATE INDEX idx_hook_targets_alert ON core.hook_targets (alert_id) WHERE alert_id IS NOT NULL;
CREATE INDEX idx_hook_targets_procedure ON core.hook_targets (procedure_id) WHERE procedure_id IS NOT NULL;

CREATE TABLE core.hook_invocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    invocation_id uuid NOT NULL,
    hook_id bigint NOT NULL,
    hook_public_id uuid NOT NULL,
    hook_name text NOT NULL,
    mode varchar(16) NOT NULL,
    status varchar(16) NOT NULL,
    accepted_at timestamptz NOT NULL,
    finished_at timestamptz,
    CONSTRAINT pk_hook_invocations PRIMARY KEY (id),
    CONSTRAINT uq_hook_invocations_invocation_id UNIQUE (invocation_id),
    CONSTRAINT ck_hook_invocations_mode CHECK (mode IN ('PARALLEL', 'SEQUENTIAL')),
    CONSTRAINT ck_hook_invocations_status CHECK (
        status IN ('RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED')
    ),
    CONSTRAINT ck_hook_invocations_finished CHECK (
        (status = 'RUNNING' AND finished_at IS NULL)
        OR (status <> 'RUNNING' AND finished_at IS NOT NULL AND finished_at >= accepted_at)
    ),
    CONSTRAINT fk_hook_invocations_hook FOREIGN KEY (hook_id)
        REFERENCES core.hooks (id) ON DELETE CASCADE
);

CREATE INDEX idx_hook_invocations_hook_accepted ON core.hook_invocations (hook_id, accepted_at DESC);
CREATE INDEX idx_hook_invocations_status ON core.hook_invocations (status, accepted_at);

CREATE TABLE core.hook_invocation_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    hook_invocation_id bigint NOT NULL,
    target_type varchar(16) NOT NULL,
    resource_id bigint NOT NULL,
    resource_name text NOT NULL,
    position integer NOT NULL,
    continue_on jsonb NOT NULL,
    busy_wait_timeout_millis bigint,
    status varchar(32) NOT NULL,
    outcome varchar(16),
    execution_id uuid,
    started_at timestamptz,
    finished_at timestamptz,
    error_code varchar(64),
    CONSTRAINT pk_hook_invocation_targets PRIMARY KEY (id),
    CONSTRAINT uq_hook_invocation_targets_position UNIQUE (hook_invocation_id, position),
    CONSTRAINT ck_hook_invocation_targets_type CHECK (target_type IN ('ALERT', 'PROCEDURE')),
    CONSTRAINT ck_hook_invocation_targets_position CHECK (position >= 0),
    CONSTRAINT ck_hook_invocation_targets_continue_on CHECK (
        jsonb_typeof(continue_on) = 'array'
        AND continue_on <@ '["SUCCESS","WARN","ERROR"]'::jsonb
    ),
    CONSTRAINT ck_hook_invocation_targets_busy_wait CHECK (
        (target_type = 'ALERT' AND busy_wait_timeout_millis > 0)
        OR (target_type = 'PROCEDURE' AND busy_wait_timeout_millis IS NULL)
    ),
    CONSTRAINT ck_hook_invocation_targets_status CHECK (
        status IN ('PENDING', 'WAITING_ALERT', 'RUNNING', 'SUCCESS', 'WARN', 'ERROR',
            'SKIPPED_DISABLED', 'SKIPPED_SEQUENCE', 'ALERT_BUSY_TIMEOUT')
    ),
    CONSTRAINT ck_hook_invocation_targets_outcome CHECK (
        outcome IS NULL OR outcome IN ('SUCCESS', 'WARN', 'ERROR')
    ),
    CONSTRAINT ck_hook_invocation_targets_time CHECK (
        started_at IS NULL OR finished_at IS NULL OR finished_at >= started_at
    ),
    CONSTRAINT fk_hook_invocation_targets_invocation FOREIGN KEY (hook_invocation_id)
        REFERENCES core.hook_invocations (id) ON DELETE CASCADE
);

CREATE INDEX idx_hook_invocation_targets_invocation_position
    ON core.hook_invocation_targets (hook_invocation_id, position);
CREATE INDEX idx_hook_invocation_targets_execution
    ON core.hook_invocation_targets (execution_id) WHERE execution_id IS NOT NULL;

CREATE TABLE audit.hooks_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    public_id uuid,
    name text,
    description text,
    enabled boolean,
    mode varchar(16),
    token_secret_id bigint,
    max_concurrent_invocations integer,
    rate_limit_count integer,
    rate_limit_window_seconds bigint,
    CONSTRAINT pk_hooks_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_hooks_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE TABLE audit.hook_targets_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    hook_id bigint,
    target_type varchar(16),
    alert_id bigint,
    procedure_id bigint,
    position integer,
    continue_on jsonb,
    busy_wait_timeout_millis bigint,
    CONSTRAINT pk_hook_targets_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_hook_targets_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_hooks_aud_rev ON audit.hooks_aud (rev);
CREATE INDEX idx_hook_targets_aud_rev ON audit.hook_targets_aud (rev);

INSERT INTO audit.log_events (code) VALUES
    ('HOOK_CREATED'),
    ('HOOK_UPDATED'),
    ('HOOK_DELETED'),
    ('HOOK_ROTATED'),
    ('HOOK_PAGE_VIEWED'),
    ('HOOK_OPTIONS_VIEWED'),
    ('HOOK_INVOCATION_ACCEPTED'),
    ('HOOK_INVOCATION_WAITING'),
    ('HOOK_INVOCATION_TIMEOUT'),
    ('HOOK_INVOCATION_COMPLETED'),
    ('HOOK_INVOCATION_REJECTED'),
    ('HOOK_INVOCATION_HISTORY_VIEWED');
