CREATE TABLE audit.logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    level varchar(16) NOT NULL,
    source text NOT NULL,
    event text NOT NULL,
    outcome varchar(16) NOT NULL,
    user_subject text NOT NULL,
    username text NOT NULL,
    request_id uuid,
    message text NOT NULL,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_logs PRIMARY KEY (id),
    CONSTRAINT ck_logs_level CHECK (level IN ('INFO', 'WARN', 'ERROR')),
    CONSTRAINT ck_logs_outcome CHECK (outcome IN ('SUCCESS', 'FAILURE')),
    CONSTRAINT ck_logs_event_not_blank CHECK (btrim(event) <> ''),
    CONSTRAINT ck_logs_source_not_blank CHECK (btrim(source) <> ''),
    CONSTRAINT ck_logs_user_subject_not_blank CHECK (btrim(user_subject) <> ''),
    CONSTRAINT ck_logs_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT ck_logs_data_object CHECK (jsonb_typeof(data) = 'object')
);

CREATE INDEX idx_logs_username ON audit.logs (username);
CREATE INDEX idx_logs_user_subject ON audit.logs (user_subject);
CREATE INDEX idx_logs_event_at ON audit.logs (event_at DESC);
CREATE INDEX idx_logs_event ON audit.logs (event);
