CREATE SCHEMA IF NOT EXISTS secrets;

CREATE TABLE secrets.secrets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    name text NOT NULL,
    description text,
    encrypted_value bytea NOT NULL,
    encryption_iv bytea NOT NULL,
    value_hash bytea NOT NULL,
    hash_salt bytea NOT NULL,
    encryption_version smallint NOT NULL,
    value_revision bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_secrets PRIMARY KEY (id),
    CONSTRAINT uq_secrets_name UNIQUE (name),
    CONSTRAINT ck_secrets_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_secrets_encrypted_value_length CHECK (octet_length(encrypted_value) >= 16),
    CONSTRAINT ck_secrets_encryption_iv_length CHECK (octet_length(encryption_iv) = 12),
    CONSTRAINT ck_secrets_value_hash_length CHECK (octet_length(value_hash) = 32),
    CONSTRAINT ck_secrets_hash_salt_length CHECK (octet_length(hash_salt) = 16),
    CONSTRAINT ck_secrets_encryption_version CHECK (encryption_version > 0),
    CONSTRAINT ck_secrets_value_revision CHECK (value_revision > 0)
);

CREATE UNIQUE INDEX uq_secrets_name_ci ON secrets.secrets (lower(name));

CREATE TABLE secrets.secret_tag (
    secret_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    tag_scope varchar(32) NOT NULL DEFAULT 'SECRET',
    CONSTRAINT pk_secret_tag PRIMARY KEY (secret_id, tag_id),
    CONSTRAINT ck_secret_tag_scope CHECK (tag_scope = 'SECRET'),
    CONSTRAINT fk_secret_tag_secret
        FOREIGN KEY (secret_id) REFERENCES secrets.secrets (id) ON DELETE CASCADE,
    CONSTRAINT fk_secret_tag_tag_scope
        FOREIGN KEY (tag_id, tag_scope) REFERENCES core.tags (id, scope) ON DELETE RESTRICT
);

CREATE INDEX idx_secret_tag_tag ON secrets.secret_tag (tag_id, secret_id);

CREATE TABLE audit.secrets_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    name text,
    description text,
    encryption_version smallint,
    value_revision bigint,
    CONSTRAINT pk_secrets_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_secrets_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_secrets_aud_rev ON audit.secrets_aud (rev);

CREATE TABLE audit.secret_tag_aud (
    secret_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    CONSTRAINT pk_secret_tag_aud PRIMARY KEY (secret_id, tag_id, rev),
    CONSTRAINT fk_secret_tag_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_secret_tag_aud_rev ON audit.secret_tag_aud (rev);

INSERT INTO audit.log_events (code) VALUES
    ('SECRET_CATALOG_ACCESSED'),
    ('SECRET_CREATED'),
    ('SECRET_DELETED'),
    ('SECRET_PAGE_VIEWED'),
    ('SECRET_TAG_CREATED'),
    ('SECRET_TAG_DELETED'),
    ('SECRET_TAG_UPDATED'),
    ('SECRET_UPDATED'),
    ('SECRET_VALUE_ACCESSED'),
    ('SECRET_VIEWED');
