INSERT INTO audit.log_events (code) VALUES
    ('WORKER_DNS_RESOLUTION_FAILED'),
    ('WORKER_DNS_RESOLUTION_RECOVERED'),
    ('WORKER_IP_AVAILABLE'),
    ('WORKER_IP_DISCOVERED'),
    ('WORKER_IP_REMOVED'),
    ('WORKER_IP_UNAVAILABLE');
