-- Consolidated execution origin, closure audit, Pipe FINALLY and resource observers.
-- Replaces the original migrations 3 through 8 for new installations.

-- Structured Pipe origin and historical parent recovery.
ALTER TABLE core.alert_executions DROP CONSTRAINT ck_alert_executions_trigger;
ALTER TABLE core.alert_executions ADD CONSTRAINT ck_alert_executions_trigger
    CHECK (trigger IS NULL OR trigger IN ('CRON', 'MANUAL', 'HOOK', 'SMART', 'PIPE'));
ALTER TABLE core.alert_executions ADD COLUMN parent_pipe_execution_id uuid;
ALTER TABLE core.alert_executions ADD COLUMN parent_step_key text;

-- The step result is authoritative, unlike the historical free-text actor.
UPDATE core.alert_executions alert
SET trigger = 'PIPE', parent_pipe_execution_id = pipe.execution_id, parent_step_key = step.step_key
FROM core.pipe_step_results step
JOIN core.pipe_executions pipe ON pipe.id = step.pipe_execution_id
WHERE step.step_type = 'ALERT' AND step.resource_execution_id = alert.execution_id;

ALTER TABLE core.alert_executions ADD CONSTRAINT ck_alert_executions_pipe_parent
    CHECK ((parent_pipe_execution_id IS NULL AND parent_step_key IS NULL)
        OR (trigger = 'PIPE' AND parent_pipe_execution_id IS NOT NULL AND parent_step_key IS NOT NULL));
CREATE INDEX idx_alert_executions_pipe_parent ON core.alert_executions (parent_pipe_execution_id)
    WHERE parent_pipe_execution_id IS NOT NULL;

-- Optional incident closure and immutable audit in its final schema.
ALTER TABLE core.alert_executions ADD COLUMN closed boolean NOT NULL DEFAULT false;
ALTER TABLE core.alert_executions ADD COLUMN closure_at timestamptz;
ALTER TABLE core.alert_executions ADD COLUMN closure_by text;
ALTER TABLE core.alert_executions ADD COLUMN closure_note text;
ALTER TABLE core.alert_executions ADD CONSTRAINT ck_alert_execution_closure
    CHECK (NOT closed OR (status IN ('WARN', 'ERROR') AND closure_at IS NOT NULL AND closure_by IS NOT NULL));

-- Preserve the audit even when an administrator deletes the original alert/history.
CREATE TABLE audit.alert_execution_closure_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id uuid NOT NULL,
    alert_id bigint NOT NULL,
    closed boolean NOT NULL,
    actor_subject text NOT NULL,
    actor_name text NOT NULL,
    note text,
    changed_at timestamptz NOT NULL DEFAULT current_timestamp,
    CONSTRAINT ck_alert_closure_note CHECK (note IS NULL OR length(note) <= 2000)
);
CREATE INDEX idx_alert_closure_audit_execution ON audit.alert_execution_closure_audit (execution_id, id);
CREATE FUNCTION audit.reject_closure_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Alert execution closure audit is immutable';
END;
$$;
CREATE TRIGGER immutable_alert_closure_audit BEFORE UPDATE OR DELETE ON audit.alert_execution_closure_audit
    FOR EACH ROW EXECUTE FUNCTION audit.reject_closure_audit_mutation();
CREATE INDEX idx_alert_executions_open_finished ON core.alert_executions (alert_id, finished_at DESC, id DESC)
    WHERE NOT closed;

-- MAIN/FINALLY phases, including the Envers history columns.
ALTER TABLE core.pipes ADD COLUMN finally_timeout_millis bigint NOT NULL DEFAULT 1800000;
ALTER TABLE core.pipes ADD CONSTRAINT ck_pipes_finally_timeout CHECK (finally_timeout_millis > 0);
ALTER TABLE audit.pipes_aud ADD COLUMN finally_timeout_millis bigint;
ALTER TABLE core.pipe_steps ADD COLUMN phase varchar(16) NOT NULL DEFAULT 'MAIN';
ALTER TABLE core.pipe_steps ADD CONSTRAINT ck_pipe_steps_phase CHECK (phase IN ('MAIN', 'FINALLY'));
ALTER TABLE audit.pipe_steps_aud ADD COLUMN phase varchar(16) DEFAULT 'MAIN';
ALTER TABLE core.pipe_step_results ADD COLUMN phase varchar(16) NOT NULL DEFAULT 'MAIN';
ALTER TABLE core.pipe_step_results ADD CONSTRAINT ck_pipe_step_results_phase CHECK (phase IN ('MAIN', 'FINALLY'));

-- Exactly one observed resource, protected from deletion while referenced.
CREATE TABLE core.alert_resource_observers (
    alert_id bigint PRIMARY KEY REFERENCES core.alerts (id) ON DELETE CASCADE,
    pipe_id bigint REFERENCES core.pipes (id) ON DELETE RESTRICT,
    procedure_id bigint REFERENCES core.procedures (id) ON DELETE RESTRICT,
    hook_id bigint REFERENCES core.hooks (id) ON DELETE RESTRICT,
    CHECK (num_nonnulls(pipe_id, procedure_id, hook_id) = 1)
);
CREATE INDEX idx_resource_observers_pipe ON core.alert_resource_observers (pipe_id) WHERE pipe_id IS NOT NULL;
CREATE INDEX idx_resource_observers_procedure ON core.alert_resource_observers (procedure_id) WHERE procedure_id IS NOT NULL;
CREATE INDEX idx_resource_observers_hook ON core.alert_resource_observers (hook_id) WHERE hook_id IS NOT NULL;

-- Observers carry a structured, sanitized summary also when the observed result is ERROR.
ALTER TABLE core.alert_executions DROP CONSTRAINT ck_alert_executions_error_fields;
ALTER TABLE core.alert_executions ADD CONSTRAINT ck_alert_executions_error_fields CHECK (
    (status IN ('SUCCESS', 'WARN') AND error_type IS NULL AND error_message IS NULL AND error_stack_trace IS NULL)
    OR (status = 'ERROR' AND error_type IS NOT NULL)
);

-- Structured Hook origin and historical invocation/name recovery.
ALTER TABLE core.alert_executions ADD COLUMN parent_hook_invocation_id uuid;
ALTER TABLE core.alert_executions ADD COLUMN parent_hook_name text;

-- Invocation targets identify the parent without interpreting the free-text actor.
-- The invocation's snapshot name survives later Hook renames and deletions.
UPDATE core.alert_executions alert
SET parent_hook_invocation_id = invocation.invocation_id,
    parent_hook_name = invocation.hook_name
FROM core.hook_invocation_targets target
JOIN core.hook_invocations invocation ON invocation.id = target.hook_invocation_id
WHERE target.target_type = 'ALERT' AND target.execution_id = alert.execution_id
    AND alert.trigger = 'HOOK' AND alert.parent_pipe_execution_id IS NULL;

ALTER TABLE core.alert_executions ADD CONSTRAINT ck_alert_executions_hook_parent
    CHECK ((parent_hook_invocation_id IS NULL AND parent_hook_name IS NULL)
        OR (trigger IS NOT NULL AND trigger = 'HOOK' AND parent_hook_invocation_id IS NOT NULL
            AND parent_hook_name IS NOT NULL AND btrim(parent_hook_name) <> ''
            AND parent_pipe_execution_id IS NULL AND parent_step_key IS NULL));
CREATE INDEX idx_alert_executions_hook_parent ON core.alert_executions (parent_hook_invocation_id)
    WHERE parent_hook_invocation_id IS NOT NULL;
