CREATE TABLE core.alert_templates (
    id text NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    name_key text NOT NULL,
    description_key text NOT NULL,
    required_capability varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_alert_templates PRIMARY KEY (id),
    CONSTRAINT ck_alert_templates_id_trimmed CHECK (id = btrim(id) AND id <> ''),
    CONSTRAINT ck_alert_templates_name_key_trimmed CHECK (name_key = btrim(name_key) AND name_key <> ''),
    CONSTRAINT ck_alert_templates_description_key_trimmed CHECK (
        description_key = btrim(description_key) AND description_key <> ''
    ),
    CONSTRAINT ck_alert_templates_required_capability CHECK (
        required_capability IN ('STANDARD', 'PLAYWRIGHT')
    )
);

CREATE INDEX idx_alert_templates_required_capability
    ON core.alert_templates (required_capability);

CREATE TABLE core.alert_template_parameters (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    alert_template_id text NOT NULL,
    parameter_key text NOT NULL,
    label_key text NOT NULL,
    description_key text NOT NULL,
    java_type text NOT NULL,
    allowed_sources jsonb NOT NULL,
    options jsonb NOT NULL DEFAULT '[]'::jsonb,
    parameter_order integer NOT NULL,
    required boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_alert_template_parameters PRIMARY KEY (id),
    CONSTRAINT uq_alert_template_parameters_template_key UNIQUE (
        alert_template_id, parameter_key
    ),
    CONSTRAINT ck_alert_template_parameters_key_trimmed CHECK (
        parameter_key = btrim(parameter_key) AND parameter_key <> ''
    ),
    CONSTRAINT ck_alert_template_parameters_label_key_trimmed CHECK (
        label_key = btrim(label_key) AND label_key <> ''
    ),
    CONSTRAINT ck_alert_template_parameters_description_key_trimmed CHECK (
        description_key = btrim(description_key) AND description_key <> ''
    ),
    CONSTRAINT ck_alert_template_parameters_java_type_trimmed CHECK (
        java_type = btrim(java_type) AND java_type <> ''
    ),
    CONSTRAINT ck_alert_template_parameters_allowed_sources CHECK (
        jsonb_typeof(allowed_sources) = 'array'
        AND jsonb_array_length(allowed_sources) > 0
        AND allowed_sources <@ '["TEXT", "CONFIGURATION", "SECRET"]'::jsonb
    ),
    CONSTRAINT ck_alert_template_parameters_options CHECK (
        jsonb_typeof(options) = 'array'
    ),
    CONSTRAINT ck_alert_template_parameters_order CHECK (parameter_order >= 0),
    CONSTRAINT fk_alert_template_parameters_template FOREIGN KEY (alert_template_id)
        REFERENCES core.alert_templates (id) ON DELETE RESTRICT
);

CREATE INDEX idx_alert_template_parameters_template_order
    ON core.alert_template_parameters (alert_template_id, parameter_order, id);

CREATE TABLE core.alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    alert_template_id text NOT NULL,
    name text NOT NULL,
    description text,
    cron_expression text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    state text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_alerts PRIMARY KEY (id),
    CONSTRAINT uq_alerts_name UNIQUE (name),
    CONSTRAINT ck_alerts_name_trimmed CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_alerts_cron_expression_trimmed CHECK (
        cron_expression = btrim(cron_expression) AND cron_expression <> ''
    ),
    CONSTRAINT fk_alerts_template FOREIGN KEY (alert_template_id)
        REFERENCES core.alert_templates (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_alerts_name_ci ON core.alerts (lower(name));
CREATE INDEX idx_alerts_template ON core.alerts (alert_template_id);
CREATE INDEX idx_alerts_enabled ON core.alerts (enabled) WHERE enabled;

CREATE TABLE core.alert_parameter_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL DEFAULT 0,
    alert_id bigint NOT NULL,
    template_parameter_id bigint NOT NULL,
    source varchar(32) NOT NULL,
    text_value text,
    configuration_id bigint,
    secret_id bigint,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_alert_parameter_values PRIMARY KEY (id),
    CONSTRAINT uq_alert_parameter_values_alert_parameter UNIQUE (
        alert_id, template_parameter_id
    ),
    CONSTRAINT ck_alert_parameter_values_source CHECK (
        source IN ('TEXT', 'CONFIGURATION', 'SECRET')
    ),
    CONSTRAINT ck_alert_parameter_values_selected_source CHECK (
        (source = 'TEXT'
            AND text_value IS NOT NULL
            AND configuration_id IS NULL
            AND secret_id IS NULL)
        OR (source = 'CONFIGURATION'
            AND text_value IS NULL
            AND configuration_id IS NOT NULL
            AND secret_id IS NULL)
        OR (source = 'SECRET'
            AND text_value IS NULL
            AND configuration_id IS NULL
            AND secret_id IS NOT NULL)
    ),
    CONSTRAINT fk_alert_parameter_values_alert FOREIGN KEY (alert_id)
        REFERENCES core.alerts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_alert_parameter_values_template_parameter FOREIGN KEY (template_parameter_id)
        REFERENCES core.alert_template_parameters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_alert_parameter_values_configuration FOREIGN KEY (configuration_id)
        REFERENCES core.configurations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_alert_parameter_values_secret FOREIGN KEY (secret_id)
        REFERENCES secrets.secrets (id) ON DELETE RESTRICT
);

CREATE INDEX idx_alert_parameter_values_template_parameter
    ON core.alert_parameter_values (template_parameter_id);
CREATE INDEX idx_alert_parameter_values_configuration
    ON core.alert_parameter_values (configuration_id) WHERE configuration_id IS NOT NULL;
CREATE INDEX idx_alert_parameter_values_secret
    ON core.alert_parameter_values (secret_id) WHERE secret_id IS NOT NULL;

CREATE TABLE core.alert_executions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    alert_id bigint NOT NULL,
    status varchar(16) NOT NULL,
    started_at timestamptz NOT NULL,
    finished_at timestamptz NOT NULL,
    status_message jsonb,
    error_type text,
    error_message text,
    error_stack_trace text,
    CONSTRAINT pk_alert_executions PRIMARY KEY (id),
    CONSTRAINT ck_alert_executions_status CHECK (status IN ('SUCCESS', 'WARN', 'ERROR')),
    CONSTRAINT ck_alert_executions_time CHECK (finished_at >= started_at),
    CONSTRAINT ck_alert_executions_error_fields CHECK (
        (status IN ('SUCCESS', 'WARN')
            AND error_type IS NULL
            AND error_message IS NULL
            AND error_stack_trace IS NULL)
        OR (status = 'ERROR' AND error_type IS NOT NULL AND btrim(error_type) <> '')
    ),
    CONSTRAINT fk_alert_executions_alert FOREIGN KEY (alert_id)
        REFERENCES core.alerts (id) ON DELETE RESTRICT
);

CREATE INDEX idx_alert_executions_alert_started
    ON core.alert_executions (alert_id, started_at DESC);
CREATE INDEX idx_alert_executions_status_started
    ON core.alert_executions (status, started_at DESC);

CREATE TABLE audit.alert_templates_aud (
    id text NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    name_key text,
    description_key text,
    required_capability varchar(32),
    CONSTRAINT pk_alert_templates_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_alert_templates_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_alert_templates_aud_rev ON audit.alert_templates_aud (rev);

CREATE TABLE audit.alert_template_parameters_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    alert_template_id text,
    parameter_key text,
    label_key text,
    description_key text,
    java_type text,
    allowed_sources jsonb,
    options jsonb,
    parameter_order integer,
    required boolean,
    CONSTRAINT pk_alert_template_parameters_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_alert_template_parameters_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_alert_template_parameters_aud_rev
    ON audit.alert_template_parameters_aud (rev);

CREATE TABLE audit.alerts_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    alert_template_id text,
    name text,
    description text,
    cron_expression text,
    enabled boolean,
    CONSTRAINT pk_alerts_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_alerts_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_alerts_aud_rev ON audit.alerts_aud (rev);

CREATE TABLE audit.alert_parameter_values_aud (
    id bigint NOT NULL,
    rev bigint NOT NULL,
    revtype smallint,
    alert_id bigint,
    template_parameter_id bigint,
    source varchar(32),
    text_value text,
    configuration_id bigint,
    secret_id bigint,
    CONSTRAINT pk_alert_parameter_values_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_alert_parameter_values_aud_rev FOREIGN KEY (rev) REFERENCES audit.revinfo (rev)
);

CREATE INDEX idx_alert_parameter_values_aud_rev
    ON audit.alert_parameter_values_aud (rev);
