ALTER TABLE core.alert_executions ADD COLUMN closed boolean NOT NULL DEFAULT false;
ALTER TABLE core.alert_executions ADD COLUMN closure_at timestamptz;
ALTER TABLE core.alert_executions ADD COLUMN closure_by text;
ALTER TABLE core.alert_executions ADD COLUMN closure_note text;
ALTER TABLE core.alert_executions ADD CONSTRAINT ck_alert_execution_closure
    CHECK (NOT closed OR (status IN ('WARN', 'ERROR') AND closure_at IS NOT NULL AND closure_by IS NOT NULL));

-- Preserve the audit even when an administrator deletes the original alert/history.
CREATE TABLE core.alert_execution_closure_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id uuid NOT NULL,
    alert_id bigint NOT NULL,
    closed boolean NOT NULL,
    actor_subject text NOT NULL,
    actor_name text NOT NULL,
    note text,
    changed_at timestamptz NOT NULL DEFAULT current_timestamp,
    CONSTRAINT ck_alert_closure_note CHECK (note IS NULL OR length(note) <= 2000)
);
CREATE INDEX idx_alert_closure_audit_execution ON core.alert_execution_closure_audit (execution_id, id);
CREATE FUNCTION core.reject_closure_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Alert execution closure audit is immutable';
END;
$$;
CREATE TRIGGER immutable_alert_closure_audit BEFORE UPDATE OR DELETE ON core.alert_execution_closure_audit
    FOR EACH ROW EXECUTE FUNCTION core.reject_closure_audit_mutation();
CREATE INDEX idx_alert_executions_open_finished ON core.alert_executions (alert_id, finished_at DESC, id DESC)
    WHERE NOT closed;
