CREATE TABLE audit.log_levels (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(32) NOT NULL,
    CONSTRAINT pk_log_levels PRIMARY KEY (id),
    CONSTRAINT uq_log_levels_code UNIQUE (code),
    CONSTRAINT ck_log_levels_code_not_blank CHECK (btrim(code) <> '')
);

CREATE TABLE audit.log_sources (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(128) NOT NULL,
    CONSTRAINT pk_log_sources PRIMARY KEY (id),
    CONSTRAINT uq_log_sources_code UNIQUE (code),
    CONSTRAINT ck_log_sources_code_not_blank CHECK (btrim(code) <> '')
);

CREATE TABLE audit.log_events (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code varchar(128) NOT NULL,
    CONSTRAINT pk_log_events PRIMARY KEY (id),
    CONSTRAINT uq_log_events_code UNIQUE (code),
    CONSTRAINT ck_log_events_code_not_blank CHECK (btrim(code) <> '')
);

INSERT INTO audit.log_levels (code)
SELECT code
FROM (
    VALUES
        ('INFO'),
        ('WARN'),
        ('ERROR')
) AS known_levels(code)
UNION
SELECT DISTINCT level
FROM audit.logs
ON CONFLICT (code) DO NOTHING;

INSERT INTO audit.log_sources (code)
SELECT 'alertify-backend'
UNION
SELECT DISTINCT source
FROM audit.logs
ON CONFLICT (code) DO NOTHING;

INSERT INTO audit.log_events (code)
SELECT code
FROM (
    VALUES
        ('API_ERROR_SHOWN'),
        ('API_REQUEST'),
        ('API_UNHANDLED_ERROR'),
        ('CONFIGURATION_CREATED'),
        ('CONFIGURATION_DELETED'),
        ('CONFIGURATION_PAGE_VIEWED'),
        ('CONFIGURATION_TAG_CREATED'),
        ('CONFIGURATION_TAG_DELETED'),
        ('CONFIGURATION_TAG_UPDATED'),
        ('CONFIGURATION_UPDATED'),
        ('CONFIGURATION_VIEWED'),
        ('USER_LOGIN')
) AS known_events(code)
UNION
SELECT DISTINCT event
FROM audit.logs
ON CONFLICT (code) DO NOTHING;

ALTER TABLE audit.logs
    ADD COLUMN level_id smallint,
    ADD COLUMN source_id smallint,
    ADD COLUMN event_id smallint;

UPDATE audit.logs AS log
SET level_id = level_catalog.id
FROM audit.log_levels AS level_catalog
WHERE level_catalog.code = log.level;

UPDATE audit.logs AS log
SET source_id = source_catalog.id
FROM audit.log_sources AS source_catalog
WHERE source_catalog.code = log.source;

UPDATE audit.logs AS log
SET event_id = event_catalog.id
FROM audit.log_events AS event_catalog
WHERE event_catalog.code = log.event;

ALTER TABLE audit.logs
    ALTER COLUMN level_id SET NOT NULL,
    ALTER COLUMN source_id SET NOT NULL,
    ALTER COLUMN event_id SET NOT NULL,
    ADD CONSTRAINT fk_logs_level
        FOREIGN KEY (level_id) REFERENCES audit.log_levels (id),
    ADD CONSTRAINT fk_logs_source
        FOREIGN KEY (source_id) REFERENCES audit.log_sources (id),
    ADD CONSTRAINT fk_logs_event
        FOREIGN KEY (event_id) REFERENCES audit.log_events (id);

DROP INDEX audit.idx_logs_event;

ALTER TABLE audit.logs
    DROP COLUMN level,
    DROP COLUMN source,
    DROP COLUMN event,
    DROP COLUMN message;

CREATE INDEX idx_logs_level_id ON audit.logs (level_id);
CREATE INDEX idx_logs_source_id ON audit.logs (source_id);
CREATE INDEX idx_logs_event_id ON audit.logs (event_id);
