server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: Alertify
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        #format_sql: true

keyPart: ${KEY_PART}
