server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: Alertify
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: ${TIME_ZONE}
        format_sql: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h

schedule: false

keyPart: ${KEY_PART}

timezoneSecondsOffset: ${TIMEZONE_SECONDS_OFFSET}