server:
  port: ${SERVER_PORT}

pageSize: 10

spring:
  application:
    name: Watchful
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        #format_sql: true
    
datasources:
  config:
    - datasource:
        name: base1
        readonly: true
        url: jdbc:postgresql://localhost:54321/base1
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
    - datasource:
        name: base2
        readonly: true
        url: jdbc:postgresql://localhost:54321/base2
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver

